<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Career_Pg.aspx.cs" Inherits="Career_Pg" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
     <title>Career</title> 
    <style>
    * { 
        margin: 0; 
        padding: 0; 
        box-sizing: border-box; 
        cursor: url("img/cursor.svg"), auto;
    } 
    
    body { 
        font-family: Arial, sans-serif; 
        background-color: #f4f4f4; 
        line-height: 1.6; 
        color: #333; 
    } 
    
    header { 
        background-color: #027b9a; 
        color: #fff; 
        text-align: center; 
        padding: 1rem 0; 
    } 
    
    nav ul { 
        list-style: none; 
        display: flex; 
        justify-content: center; 
        background-color: #746f6f; 
        padding: 0.5rem 0; 
    } 
    
    nav li { 
        margin-right: 20px; 
    } 
    
    nav a { 
        text-decoration: none; 
        color: #fff; 
        font-weight: bold; 
        transition: color 0.3s; 
    } 
    
    nav a:hover { 
        color: #ff6600; 
    } 
    
    .search { 
        text-align: center; 
        margin-top: 2rem; 
    } 
    
    .search h2 { 
        font-size: 24px; 
        margin-bottom: 1rem; 
    } 
    
    .search form { 
        display: flex; 
        justify-content: center; 
        align-items: center; 
    } 
    
    .search input[type="text"], .search input[type="email"] { 
        padding: 10px; 
        margin-right: 10px; 
        border: 1px solid #ccc; 
        border-radius: 4px; 
    } 
    
    .search button { 
        background-color: #ff6600; 
        color: #fff; 
        border: none; 
        padding: 10px 20px; 
        border-radius: 4px; 
        cursor: pointer; 
        transition: background-color 0.3s; 
    } 
    
    .search button:hover { 
        background-color: #ff3300; 
    } 
    
    .job-listings { 
        margin: 2rem 0; 
    } 
    
    .job-listings h2 { 
        font-size: 24px; 
        margin-bottom: 1rem; 
        text-align: center; 
    } 
    
    
    
    .job-listings h3 { 
        font-size: 20px; 
        margin-bottom: 10px; 
    } 
    
    .job-listings p { 
        font-size: 14px; 
        margin-bottom: 10px; 
    } 
    
    .job-listings a { 
        background-color: #333; 
        color: #fff; 
        text-decoration: none; 
        padding: 10px 20px; 
        border-radius: 4px; 
        display: inline-block; 
        transition: background-color 0.3s; 
    }
    
    .main{
        display: flex;
        flex-direction: row;
        justify-content: space-around;
        margin-top: 15px;
        margin-bottom: 10px;
    }

    .cat{
        width: 300px;
    }

    h2{
        padding-bottom: 5px;
    }
    
    .job-listings a:hover { 
        background-color: #ff6600; 
    } 
    
    footer { 
        text-align: center; 
        background-color: #333; 
        color: #fff; 
        padding: 1rem 0; 
    }
    </style>
</head>
<body>
     <header> 
		<h1>Job Search Portal</h1> 
	</header> 
	<nav> 
		<ul> 
			<li><a href="Home.aspx">Home</a></li> 
			<li><a href="Career_Pg.aspx">Jobs</a></li> 
			<li><a href="#">About Us</a></li> 
			<li><a href="contact_us.aspx">Contact</a></li> 
		</ul> 
	</nav> 
	<section class="search"> 
		<h2>Find Your Job</h2> 
		<form action="https://api.web3forms.com/submit" method="POST"> 
            <input type="hidden" name="access_key" value="3365e40a-1315-40e0-ae8c-dc3c93300efb">
			<input type="text" name="Name"
				placeholder="Name"> 
			<input type="email" name="email"
				placeholder="email"> 
			<input type="text" name="position"
				placeholder="Position"> 
                <div class="h-captcha" data-captcha="true"></div>
			<button type="submit"> 
				Submit 
			</button> 
		</form> 
        <script src="https://web3forms.com/client/script.js" async defer></script>
	</section> 

        <div class="main">
            <div class="cat">
                <h2>Document Controller</h2> 
                <p>The  Document Controller is responsible for controlling the numbering, filing, sorting, distribution and retrieval of electronically stored / hard copy project documentation generated by various stake holders (Internal & External) in a timely, accurate and efficient manner. Following are responsibilities

                    Uploading & Downloading of Drawings / Documents to/ from Documentation system
                    Maintaining project documentation in structured manner for easy accessibility, distribute as per approved matrix within for review.
                    Interact with TFD personnel, Consultants and Vendors to ensure that all latest documents are available.</p>
            </div>
            <div class="cat">
                <h2>Business Development Manager</h2> 
                <p>We are a start-up, and if you have the passion and rigor to join in the growth journey, this place is meant for you. TFD gives immense opportunities for all to grow and earn. You just have to perform!

                    The Primary role and responsibilities of a BDM include:
                    
                    Build contacts with clients & create business opportunities.
                    Keep the prospective client database updated. - Make calls to new business leads.
                    Write tailor-made business proposals.</p>
            </div>
            <div class="cat">
                <h2>Intern</h2> 
                <p>Ever since we have initiated our services in Delhi, Mumbai, and Bangalore, we have been receiving love and appreciation. It delights us to announce that we are expanding and for that, we are looking for some young talents that can support us in extending The Fuel Delivery family. The internship would be for the duration of three months.

                    We are looking for interns with:
                    
                    Self-confident attitude
                    Aptitude to learn
                    Diligent work Ethic
                    Innovative mindset
                    Teamwork spirit</p>
            </div>
        </div>
	
	<footer> 
		<p>© 2023 Fuel Flow Job Search Portal</p> 
	</footer> 
</body>
</html>
